### ISSUE TITLE
댓글 시스템 구축하기

### ISSUE THREAD

**Issue by yoonjong-park** [YooGenie/YooGenie.github.io#1]
https://ahnjg.tistory.com/53

https://disqus.com/

화이팅
😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆

**Comment by YooGenie** [comment]
@yoonjong-park  댓글 시스템 안하려고 했는데.. 2월에 해볼게요

**Comment by yoonjong-park** [comment]
@YooGenie 
점점 더 멀어져간다
머물러 있는 2월인 줄 알았는데~♪ ㅋㅋㅋㅋ

**Comment by YooGenie** [comment]
다시 깃블로그 말고 티스토리로 이동
